name: Docs2Pages
on: [push, pull_request, workflow_dispatch]
permissions:
  contents: write

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install Poetry
      uses: snok/install-poetry@v1

    - name: Install dependencies
      run: |
        poetry install --with dev

    - name: Sphinx build
      run: |
        poetry run sphinx-build -b html docs/source docs/build/html

    - name: Deploy documentation
      uses: peaceiris/actions-gh-pages@v4
      if: github.event_name == 'push' && github.ref == 'refs/heads/docs'
      with:
        publish_branch: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/build/html
        force_orphan: true