name: Docs2Pages
on: [push, pull_request, workflow_dispatch]
permissions:
  contents: write

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - uses: actions/setup-python@v4
    - uses: abatilo/actions-poetry@v2.1.3
    - name: install
      run: poetry install -E amazon -E docs
    - name: Sphinx build
      run: |
        sphinx-build -b html docs/source docs/build/html
    - name: Deploy documentation
      uses: peaceiris/actions-gh-pages@v3
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      with:
        publish_branch: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/build/html
        force_orphan: true